baseurl: 		""
title: 			The Digital Insurer

name: 			The Digital Insurer
description: 	UK insurance companies doing interesting things with technology
url: 			"http://thedigitalinsurer.co.uk"

twitter: 		insurancebyjack
email: 			hello@insurancebyjack.co.uk

analytics: 		UA-XXXXXXX-Y

permalinks: 	pretty