baseurl: 		""
title: 			The Digital Insurer

name: 			The Digital Insurer
description: 	UK insurance companies doing interesting things with design and technology
url: 			"http://thedigitalinsurer.co.uk"

twitter: 		insurancebyjack
email: 			hello@insurancebyjack.co.uk

permalinks: 	pretty